export const GET_SEARCH_ITEMS_REQUEST = 'GET_SEARCH_ITEMS_REQUEST';
export const GET_SEARCH_ITEMS_SUCCESS = 'GET_SEARCH_ITEMS_SUCCESS';
export const GET_SEARCH_ITEMS_FAILURE = 'GET_SEARCH_ITEMS_FAILURE';

export const GET_FILTER_ITEMS = 'GET_FILTER_ITEMS';
